workflows:
  expo_android_internal:
    name: Expo Android (AAB + Internal Testing)

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    environment:
      groups:
        - google_credentials
        - vidkar
      vars:
        NODE_VERSION: 22
      node: 22
      java: 17

    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Expo prebuild
        script: |
          rm -rf android
          npx expo prebuild --platform android

      - name: Inject signingConfig into build.gradle
        script: |
          sed -i '' 's/android {/android {\n    signingConfigs {\n        release {\n            storeFile file($CM_KEYSTORE_PATH)\n            storePassword $CM_KEYSTORE_PASSWORD\n            keyAlias $CM_KEY_ALIAS\n            keyPassword $CM_KEY_PASSWORD\n        }\n    }\n/g' android/app/build.gradle

          sed -i '' 's/buildTypes {/buildTypes {\n        release {\n            signingConfig signingConfigs.release\n        }\n/g' android/app/build.gradle

      - name: Set versionCode
        script: |
          cd android/app
          perl -pi -e "s/versionCode\s+\d+/versionCode $PROJECT_BUILD_NUMBER/g" build.gradle

      - name: Build AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

      email:
        recipients:
          - "carlosmbinf@gmail.com"
        notify:
          success: true
          failure: true
