workflows:
  deploy_internal_tester:
    name: Internal Tester - React Native Android Build & Upload to Google Play
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
        - vidkar
      vars:
        NODE_VERSION: 20
      java: 17

    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
        - android/.gradle
        - android/app/build
        - ~/.npm
        
    scripts:
      - name: Show build number
        script: |
          echo "Build number is: $PROJECT_BUILD_NUMBER "

      - name: Export build number as env var for gradle
        script: |
          export BUILD_NUMBER=$PROJECT_BUILD_NUMBER 
          echo "BUILD_NUMBER=$BUILD_NUMBER"

      - name: Install dependencies
        script: |
          npm install -f

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      # - name: Build APK Release
      #   script: |
      #     cd android
      #     ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      # - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

      slack:
        channel: "#deploys"
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      email:
        recipients:
          - "carlosmbinf@gmail.com"
          - "manumedinap0107@gmail.com"
          - "yaimaduartes@gmail.com"
        notify:
          success: true

  deploy_produccion:
    name: Production - React Native Android Build & Upload to Google Play
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
        - vidkar
      vars:
        NODE_VERSION: 20
      java: 17

    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
        - android/.gradle
        - android/app/build
        - ~/.npm
        
    scripts:
      - name: Show build number
        script: |
          echo "Build number is: $PROJECT_BUILD_NUMBER "

      - name: Export build number as env var for gradle
        script: |
          export BUILD_NUMBER=$PROJECT_BUILD_NUMBER 
          echo "BUILD_NUMBER=$BUILD_NUMBER"

      - name: Install dependencies con yarn (opcional)
        script: |
          yarn install --legacy-peer-deps

      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      # - name: Build APK Release
      #   script: |
      #     cd android
      #     ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      # - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: production

      slack:
        channel: "#deploys_production"
        notify_on_build_start: true
        notify:
          success: true
          failure: true

      email:
        recipients:
          - "carlosmbinf@gmail.com"
          # - "honoriopompahernandez@gmail.com"
          - "manumedinap0107@gmail.com"
          - "yaimaduartes@gmail.com"
          # - "eu9023@gmail.com"
          # - "osmedebello74@gmail.com"
        notify:
          success: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: VidkarAPIKey    # nombre de la integración creada en Codemagic UI
    environment:
      vars:
        XCODE_WORKSPACE: "Vidkar.xcworkspace"     # ajusta si tu workspace tiene otro nombre
        XCODE_SCHEME: "Vidkar"                    # ajusta si tu scheme tiene otro nombre
        APP_ID: 6751348594                        # App Store Connect - Apple ID (número)
        BUNDLE_ID: "com.vidkar"                   # Bundle Identifier exacto
      node: 18
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install npm dependencies
        script: |
          npm install -f

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Initialize keychain and fetch signing files
        script: |
          # crea/abre un keychain en la VM y descarga/crea certificados y provisioning profiles
          keychain initialize

          # fetch-signing-files usará la integración App Store Connect configurada
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

          # añade los certificados al keychain actual
          keychain add-certificates

          # aplica los provisioning profiles y settings al proyecto Xcode
          xcode-project use-profiles

      - name: Increment build number (optional)
        script: |
          cd $CM_BUILD_DIR/ios
          # obtiene el ultimo build number de TestFlight y suma 1
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0)
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
          echo "New build number: $NEW_BUILD_NUMBER"
          cd $CM_BUILD_DIR

      - name: Build ipa for distribution
        script: |
          # build-ipa usa la configuración aplicada por xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group carlitoPruebas

      email:
        recipients:
          - "carlosmbinf@gmail.com"
        notify:
          success: true
          failure: true

  ios_release_build:
    name: iOS Release – React Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: VidkarAPIKey
    environment:
      vars:
        XCODE_WORKSPACE: "Vidkar.xcworkspace"          # Ajustar si cambia
        XCODE_SCHEME: "Vidkar"
        APP_ID: 6751348594
        BUNDLE_ID: "com.vidkar"
        NODE_VERSION: 18
        # SELF_SIGNED_CERT_BASE64: (Definir en UI si se usa un cert autofirmado para QA)
      node: 18
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - node_modules
        - ios/Pods
        - $HOME/Library/Caches/CocoaPods
        - ~/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Mostrar variables base
        script: |
          echo "Node $(node -v)"
          echo "Workspace: $XCODE_WORKSPACE | Scheme: $XCODE_SCHEME"

      - name: Instalar dependencias npm (forzado)
        script: |
          npm install -f

      - name: Instalar dependencias CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Importar certificado autofirmado (opcional)
        script: |
          if [ -n "$SELF_SIGNED_CERT_BASE64" ]; then
            echo "$SELF_SIGNED_CERT_BASE64" | base64 --decode > selfsigned.cer
            security import selfsigned.cer -k "$HOME/Library/Keychains/login.keychain-db" -A || true
            security add-trusted-cert -d -r trustRoot -k "$HOME/Library/Keychains/login.keychain-db" selfsigned.cer || true
            echo "Certificado autofirmado importado."
          else
            echo "No se definió SELF_SIGNED_CERT_BASE64. Se omite importación."
          fi

      - name: Inicializar keychain y perfiles
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Incrementar build number desde TestFlight
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID" || echo 0)
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
          echo "Nuevo build number: $NEW_BUILD_NUMBER"
          cd ..

      - name: Compilar IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group carlitoPruebas
      email:
        recipients:
          - "carlosmbinf@gmail.com"
        notify:
          success: true
          failure: true