workflows:
  deploy_internal_tester:
    name: Internal Tester - React Native Android Build & Upload to Google Play
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
        - vidkar
      vars:
        NODE_VERSION: 18
      java: 17

    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
        - android/.gradle
        - android/app/build
        - ~/.npm
        
    scripts:
      - name: Show build number
        script: |
          echo "Build number is: $PROJECT_BUILD_NUMBER "

      - name: Export build number as env var for gradle
        script: |
          export BUILD_NUMBER=$PROJECT_BUILD_NUMBER 
          echo "BUILD_NUMBER=$BUILD_NUMBER"

      - name: Install dependencies
        script: |
          npm install -f

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      # - name: Build APK Release
      #   script: |
      #     cd android
      #     ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      # - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

      slack:
        channel: "#deploys"
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      email:
        recipients:
          - "carlosmbinf@gmail.com"
          - "manumedinap0107@gmail.com"
          - "yaimaduartes@gmail.com"
        notify:
          success: true

  deploy_produccion:
    name: Production - React Native Android Build & Upload to Google Play
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
        - vidkar
      vars:
        NODE_VERSION: 18
      java: 17

    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - node_modules
        - android/.gradle
        - android/app/build
        - ~/.npm
        
    scripts:
      - name: Show build number
        script: |
          echo "Build number is: $PROJECT_BUILD_NUMBER "

      - name: Export build number as env var for gradle
        script: |
          export BUILD_NUMBER=$PROJECT_BUILD_NUMBER 
          echo "BUILD_NUMBER=$BUILD_NUMBER"

      - name: Install dependencies
        script: |
          npm install -f

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      # - name: Build APK Release
      #   script: |
      #     cd android
      #     ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      # - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: production

      slack:
        channel: "#deploys_production"
        notify_on_build_start: true
        notify:
          success: true
          failure: true

      email:
        recipients:
          - "carlosmbinf@gmail.com"
          - "honoriopompahernandez@gmail.com"
          - "manumedinap0107@gmail.com"
          - "yaimaduartes@gmail.com"
          - "eu9023@gmail.com"
          - "osmedebello74@gmail.com"
        notify:
          success: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      #ios_signing:
       # distribution_type: app_store
        #bundle_identifier: com.vidkar
      vars:
        XCODE_WORKSPACE: "Vidkar.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "Vidkar" # <-- Put the name of your Xcode scheme here
        APP_ID: 6751348594 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        BUNDLE_ID: "com.vidkar" # <- agregado para los comandos de firma
      node: v19.7.0
      xcode: latest
      cocoapods: default
    scripts:
        - name: Install npm dependencies
          script: |
            npm install
        - name: Install CocoaPods dependencies
          script: |
            cd ios && pod install
        - name: Set up code signing settings on Xcode project
          script: |
            # Inicializa llavero y obtiene/crea perfiles de distribución App Store para el bundle id
            keychain initialize
            app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
            keychain add-certificates
            # Aplica los perfiles al proyecto
            xcode-project use-profiles
        - name: Increment build number
          script: |
            cd $CM_BUILD_DIR/ios
            LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
            agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa \
              --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME"
    artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - carlosmbinf@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group carlitoPruebas

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false