workflows:
  react-native-android-play:
    name: React Native Android Build & Upload to Google Play
    environment:
      groups:
        - google_credentials # aquí debes tener las credenciales de Google Play
        - vidkar             # aquí debes tener tus variables: KEYSTORE_BASE64, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
      vars:
        NODE_VERSION: 18
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install -f

      - name: Decode keystore
        script: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.jks
          export KEYSTORE_FILE=my-release-key.jks
          echo "KEYSTORE_FILE=$KEYSTORE_FILE" >> "$CM_ENV_FILE"

      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Build APK Release
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
