workflows:
  expo_android_internal:
    name: Expo Android (AAB + Internal Testing)

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
        - vidkar
      node: 22
      java: 17

    cache:
      cache_paths:
        - node_modules
        - ~/.npm
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Fix Expo dependencies
        script: |
          npx expo install --fix

      - name: Install Expo CLI
        script: |
          npm install -g expo-cli

      - name: Clean previous builds
        script: |
          rm -rf android

      - name: Expo prebuild (generate native project)
        script: |
          npx expo prebuild --platform android

      - name: Set dynamic versionCode
        script: |
          echo "Build number: $PROJECT_BUILD_NUMBER"

          cd android/app
          perl -pi -e "s/versionCode\s+\d+/versionCode $PROJECT_BUILD_NUMBER/g" build.gradle

      - name: Build AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal

      email:
        recipients:
          - "carlosmbinf@gmail.com"
        notify:
          success: true
          failure: true
