import { StyleSheet } from "react-native";

export const getLoginPalette = (isDarkMode) =>
  isDarkMode
    ? {
        altText: "rgba(226, 232, 240, 0.82)",
        backgroundOverlay: "rgba(4, 10, 24, 0.1)",
        blurCardAccent: "rgba(96, 165, 250, 0.14)",
        blurCardBorder: "rgba(255,255,255,0.18)",
        blurCardGlow: "rgba(59, 130, 246, 0.18)",
        blurCardOverlay: "rgba(5, 10, 22, 0.28)",
        blurCardSheen: "rgba(255,255,255,0.08)",
        brandDescription: "rgba(226, 232, 240, 0.86)",
        brandEyebrow: "#93c5fd",
        brandHighlightBorder: "rgba(148, 163, 184, 0.16)",
        brandHighlightLabel: "rgba(191, 219, 254, 0.78)",
        brandHighlightSurface: "rgba(15, 23, 42, 0.34)",
        brandHighlightValue: "#ffffff",
        brandTitle: "#ffffff",
        divider: "rgba(148, 163, 184, 0.2)",
        footerText: "rgba(226, 232, 240, 0.74)",
        formDescription: "rgba(226, 232, 240, 0.78)",
        formEyebrow: "#93c5fd",
        formMetaSurface: "rgba(15, 23, 42, 0.46)",
        formMetaText: "#dbeafe",
        formTitle: "#ffffff",
        inputBackground: "rgba(255,255,255,0.08)",
        inputBorder: "rgba(191, 219, 254, 0.14)",
        inputLabel: "#cbd5e1",
        inputText: "#f8fafc",
        inputTint: "#93c5fd",
        secondaryButtonBorder: "rgba(191, 219, 254, 0.22)",
        secondaryButtonText: "#e2e8f0",
        serverCardBorder: "rgba(148, 163, 184, 0.16)",
        serverCardSurface: "rgba(15, 23, 42, 0.22)",
        serverLabel: "rgba(226, 232, 240, 0.8)",
        statusText: "#93c5fd",
      }
    : {
        altText: "rgba(226, 232, 240, 0.78)",
        backgroundOverlay: "rgba(4, 10, 24, 0.08)",
        blurCardAccent: "rgba(96, 165, 250, 0.12)",
        blurCardBorder: "rgba(255,255,255,0.16)",
        blurCardGlow: "rgba(59, 130, 246, 0.16)",
        blurCardOverlay: "rgba(5, 10, 22, 0.24)",
        blurCardSheen: "rgba(255,255,255,0.08)",
        brandDescription: "rgba(226, 232, 240, 0.82)",
        brandEyebrow: "#93c5fd",
        brandHighlightBorder: "rgba(148, 163, 184, 0.16)",
        brandHighlightLabel: "rgba(191, 219, 254, 0.74)",
        brandHighlightSurface: "rgba(15, 23, 42, 0.3)",
        brandHighlightValue: "#ffffff",
        brandTitle: "#ffffff",
        divider: "rgba(148, 163, 184, 0.2)",
        footerText: "rgba(226, 232, 240, 0.72)",
        formDescription: "rgba(226, 232, 240, 0.76)",
        formEyebrow: "#93c5fd",
        formMetaSurface: "rgba(15, 23, 42, 0.42)",
        formMetaText: "#dbeafe",
        formTitle: "#ffffff",
        inputBackground: "rgba(255,255,255,0.08)",
        inputBorder: "rgba(191, 219, 254, 0.12)",
        inputLabel: "#cbd5e1",
        inputText: "#f8fafc",
        inputTint: "#93c5fd",
        secondaryButtonBorder: "rgba(191, 219, 254, 0.2)",
        secondaryButtonText: "#e2e8f0",
        serverCardBorder: "rgba(148, 163, 184, 0.16)",
        serverCardSurface: "rgba(15, 23, 42, 0.2)",
        serverLabel: "rgba(226, 232, 240, 0.78)",
        statusText: "#93c5fd",
      };

export const loginScreenStyles = StyleSheet.create({
  altText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
    textAlign: "center",
    textTransform: "uppercase",
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  blurCard: {
    backgroundColor: "transparent",
    borderRadius: 34,
    borderWidth: 1,
    overflow: "hidden",
    position: "relative",
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.26,
    shadowRadius: 34,
    width: "100%",
  },
  blurCardContent: {
    alignItems: "stretch",
    paddingHorizontal: 28,
    paddingVertical: 30,
  },
  blurGlowOrb: {
    borderRadius: 120,
    height: 220,
    position: "absolute",
    right: -62,
    top: -82,
    width: 220,
  },
  blurGlowOrbSecondary: {
    borderRadius: 90,
    bottom: -72,
    height: 170,
    left: -34,
    position: "absolute",
    width: 170,
  },
  blurSheen: {
    borderRadius: 90,
    height: 180,
    left: -26,
    position: "absolute",
    top: -76,
    transform: [{ rotate: "-8deg" }],
    width: 260,
  },
  brandBadge: {
    alignItems: "center",
    backgroundColor: "rgba(37, 99, 235, 0.24)",
    borderColor: "rgba(191, 219, 254, 0.18)",
    borderRadius: 28,
    borderWidth: 1,
    height: 84,
    justifyContent: "center",
    marginBottom: 22,
    width: 84,
  },
  brandDescription: {
    fontSize: 16,
    lineHeight: 26,
    maxWidth: 520,
  },
  brandEyebrow: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.2,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  brandHighlightCard: {
    borderRadius: 20,
    borderWidth: 1,
    minWidth: 148,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  brandHighlightLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  brandHighlights: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 30,
  },
  brandHighlightValue: {
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
  },
  brandPanel: {
    justifyContent: "center",
  },
  brandPanelStacked: {
    marginBottom: 24,
    width: "100%",
  },
  brandPanelWide: {
    flex: 1,
    maxWidth: 560,
    paddingRight: 26,
  },
  brandTitle: {
    fontSize: 44,
    fontWeight: "900",
    letterSpacing: 1.6,
    lineHeight: 50,
    marginBottom: 16,
  },
  screen: {
    flex: 1,
  },
  dividerLine: {
    flex: 1,
    height: 1,
  },
  dividerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
    marginTop: 4,
  },
  fieldsBlock: {
    gap: 12,
    marginBottom: 20,
  },
  footerPanel: {
    marginTop: 18,
  },
  footerText: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  formDescription: {
    fontSize: 14,
    lineHeight: 22,
  },
  formEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  formHeader: {
    marginBottom: 24,
  },
  formMetaPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  formMetaPillText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  formMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 16,
  },
  formPanel: {
    maxWidth: 480,
    width: "100%",
    borderRadius: 32,
  },
  safeArea: {
    flex: 1,
  },
  input: {
    width: "100%",
  },
  layoutShell: {
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: "auto",
    width: "100%",
  },
  layoutShellStacked: {
    maxWidth: 560,
  },
  layoutShellWide: {
    columnGap: 32,
    flexGrow: 1,
    flexDirection: "row",
    justifyContent: "center",
    maxWidth: 1180,
  },
  mainLandscape: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  mainPortrait: {
    flexDirection: "column",
  },
  primaryButton: {
    borderRadius: 16,
    marginTop: 2,
  },
  primaryButtonContent: {
    height: 52,
  },
  primaryButtonLabel: {
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  reconnectButton: {
    borderRadius: 14,
    height: 52,
  },
  reconnectButtonContent: {
    height: 52,
    paddingHorizontal: 4,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  scrollContentCentered: {
    justifyContent: "center",
  },
  scrollContentStacked: {
    justifyContent: "flex-start",
  },
  serverRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  serverCard: {
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 18,
    padding: 14,
  },
  serverInput: {
    flex: 1,
  },
  serverLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  socialButtons: {
    gap: 10,
  },
  socialSection: {
    marginTop: 18,
  },
  secondaryButton: {
    borderRadius: 16,
  },
  secondaryButtonContent: {
    height: 50,
  },
  statusText: {
    marginTop: 12,
    textAlign: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 34,
    marginBottom: 10,
    textAlign: "left",
  },
});
